#' Load a matrix from a file
#'
#' The predict.cdcosso function is a function that receives the object and test data (testx) of the cdcosso package as input
#' and generates a predicted value for the test data.
#' This function uses the given test data to calculate predictions from the weights and biases generated by the model.
#'
#' @param model Fitted model from cdcosso.
#' @param testx A new dataset to predict.
#'
#' @return A list containing the predicted value for the new dataset.
#' @export

predict.cdcosso = function(model, testx)
{
  family = model$family
  if(family == "gaussian") fam = gaussian()
  if(family == "binomial") fam = binomial()
  if(family == "poisson") fam = poisson()

  tr_n = dim(model$data$x)[1]
  te_n <- dim(testx)[1]

  if(class(testx)[1] == "data.frame") testx = matrix(unlist(testx), nrow = te_n)
  testx = apply(testx, 2, rescale)
  K = make_anovaKernel(testx, model$data$x, model$data$kernel, model$data$kparam)

  d = K$numK
  R = array(NA, c(te_n, tr_n, d))

  for(j in 1:d){
    R[, , j] = K$K[[j]]
  }

  wt = rep(1, d)
  Rtheta <- wsGram(R, model$theta_step$theta.new/wt^2)

  c.new = model$c_step$c.new
  f.new = c(Rtheta %*% c.new + model$c_step$b.new)

  if(family != "Cox"){
    mu.new = fam$linkinv(f.new)
    out = list(f.new = f.new, mu.new = mu.new)
  }

  if(family == "Cox"){
    out = list(K.new = K, f.new = f.new)
  }

  return(out)
}


