#' Load a matrix from a file
#'
#' The predict.cdcosso function is a function that receives the object and test data (testx) of the cdcosso package as input
#' and generates a predicted value for the test data.
#' This function uses the given test data to calculate predictions from the weights and biases generated by the model.
#'
#' @param object Fitted model from cdcosso.
#' @param testx A new dataset to predict.
#'
#' @return A list containing the predicted value for the new dataset.
#' @export

predict.cdcosso = function(object, testx)
{
  tr_n = dim(object$data$x)[1]
  te_n <- dim(testx)[1]

  if(class(testx)[1] == "data.frame") testx = matrix(unlist(testx), nrow = te_n)
  testx = apply(testx, 2, rescale)
  K = make_anovaKernel(testx, object$data$x, object$data$kernel, object$data$kparam)

  d = K$numK
  R = array(NA, c(te_n, tr_n, d))

  for(j in 1:d){
    R[, , j] = K$K[[j]]
  }

  wt = rep(1, d)
  Rtheta <- wsGram(R, object$theta_step$theta.new/wt^2)

  c.new = object$c_step$c.new
  f.new = c(Rtheta %*% c.new + object$c_step$b.new)

  if(object$object$family != "Cox"){
    mu.new = object$object$linkinv(f.new)
    out = list(f.new = f.new, mu.new = mu.new)
  }

  if(object$object$family == "Cox"){
    out = list(f.new = f.new)
  }

  return(out)
}


