#' Load a matrix from a file
#'
#' The predict.cdcosso function is a function that receives the object and test data (testx) of the cdcosso package as input
#' and generates a predicted value for the test data.
#' This function uses the given test data to calculate predictions from the weights and biases generated by the model.
#'
#' @param model Fitted model from cdcosso.
#' @param testx A new dataset to predict.
#'
#' @return A list containing the predicted value for the new dataset.
#' @export

predict.cdcosso = function(model, testx)
{
  family = model$family
  if(family == "gaussian") obj = gaussian()
  if(family == "binomial") obj = binomial()
  if(family == "poisson") obj = poisson()

  nbasis = length(model$data$basis.id)
  te_n <- dim(testx)[1]

  if(class(testx)[1] == "data.frame") testx = matrix(unlist(testx), nrow = te_n)
  testx = pnorm(testx)

  K = make_anovaKernel(testx, model$data$x[model$data$basis.id, ], model$data$kernel, model$data$kparam)
  d = K$numK

  R = array(NA, c(te_n, nbasis, d))
  for(j in 1:d){
    R[, , j] = K$K[[j]]
  }

  Rtheta <- combine_kernel(R, model$theta_step$theta.new/(model$data$wt^2))

  f.new = c(Rtheta %*% model$c_step$c.new + model$c_step$b.new)

  rm(K)
  rm(R)
  rm(Rtheta)

  if(family != "Cox"){
    out = list(f.new = f.new, mu.new = obj$linkinv(f.new))
  }

  if(family == "Cox"){
    out = list(K.new = Rtheta, f.new = f.new)
  }

  return(out)
}
