#' Load a matrix from a file
#'
#' The predict.cdcosso function is a function that receives the object and test data (testx) of the cdcosso package as input
#' and generates a predicted value for the test data.
#' This function uses the given test data to calculate predictions from the weights and biases generated by the model.
#'
#' @param y Model object fitted from the cdcosso package.
#' @param test_percent The test data you want to predict.
#'
#' @return a list containing the predicted value for the test data (f.new) and the transformed value of that predicted value (mu.new).
#' @export
train_test_split = function(y, test_percent){
  y = as.numeric(as.factor(y))
  tb = table(y)
  uniq_label = as.numeric(names(tb))
  num = floor(tb * test_percent)

  test_id = c()
  for(i in 1:length(tb)){
    test_id = c(test_id, sort(sample(which(y == i), num[i], replace = FALSE)))
  }

  out = list()
  out$train_id = which(!((1:length(y)) %in% test_id))
  out$test_id = which((1:length(y)) %in% test_id)

  return(out)
}
